### PR TITLE
various improvements

### LINKED ISSUE #6: mask visualization does not always work
I have COCO datasets for PNGs in RGB colorspace, with segmentation converted from polygons to RLE format prior to starting COCO Explorer.

But on some images, this happens when activating `Draw prediction masks`:
```
ValueError: operands could not be broadcast together with shapes (56179,) (3,)
Traceback:
File "/opt/conda/lib/python3.7/site-packages/streamlit/ScriptRunner.py", line 322, in _run_script
    exec(code, module.__dict__)
File "/cocodemo/coco_explorer.py", line 153, in <module>
    app(args)
File "/cocodemo/coco_explorer.py", line 65, in app
    figsize=(15, 15))
File "/cocodemo/cocoinspector.py", line 172, in visualize_image
    draw_pred_mask=draw_pred_mask)
File "/cocodemo/vis.py", line 60, in vis_image
    img[mask] = img[mask] * 0.5 + color_mask * 0.5
```

What am I doing wrong?

(Also, I can see nothing when activating `Draw ground truth masks`...)

### PR DESCRIPTION
**Pull request by bertsky**
Fixes #6 and #9. If this all-at-once PR is inconvenient, I can also split it up functionally.

I've also changed the `st.image(figure.savefig())` to `st.pyplot(figure)` because that seemed faster. It depends on the image resolution and `dpi` parameter for `savefig` though. Still, it seems more logical that way. The single parameter to control the size/speed trade-off would be `figsize` then. Perhaps we should make that configurable?

I have also added an input field to look up images by file_name (which is helpful for navigation in large datasets), and an option to make the category view show only that single category.

### CODE REVIEW

**Comment by bertsky** [comment]
> The single parameter to control the size/speed trade-off would be `figsize` then. Perhaps we should make that configurable?

Added that as well. This really helps browsing faster through a large dataset (with lower resolution), while still allowing high-res when needed.

I have also redefined the `GT` annotation type now: `pred` was completely redundant, but what's really needed is a distinction between false negatives / GT misses and GT in general. For example, one might want to view just TP/FP/TN, or just GT.

Lastly, I found a way to deal with overlapping labels by integrating a nice [tool](https://github.com/Phlya/adjustText) for mag(net)ic artist placement in matplotlib:

screenshot

(I tried with `mpl_connect("motion_notify_event", hover_func)` but found that `st.pyplot` does not wrap events at all. Perhaps a mouse hover functionality could be arrived at via plotly instead of matplotlib?)

**Comment by i008** [comment]
Amazing  contribiutions! thanks a lot. One issue i found is when using the select image by path:
when i just use the path printed (full path to image) i get:

image
image

Any idea whats happening?

**Comment by bertsky** [comment]
> Any idea whats happening?

Oh, sorry. I confused image_id with image number there (again). Should be fixed now.

**Comment by i008** [comment]
Great, thanks a lot!

**Pull request merged**
