### PR TITLE
Variable IoU

### PR DESCRIPTION
**Pull request by bertsky**
Here's more :grin:

With this you can also select a different mode of comparison during startup (e.g. `segm` instead of `bbox`), and vary the overlap criterion for `COCOEval` (which gets reflected in statistics, too).

### CODE REVIEW

**Comment by bertsky** [comment]
Or maybe the IoU selection double slider is too much (esp. for smaller screens)? Having the option to change this on start-up would probably be sufficient... (as is also possible now via `--iou_min`)

**Comment by i008** [comment]
Hey i added you as a colaborator, seems like you have a better idea whats going on then i ever  did :D i did not use it extensively at any point was more "a i want to see how streamlit works" project.

Anyhow its really great  to see that sometimes people find - even a buggy project useful -  and willing to fix/improve  it.

**Comment by bertsky** [comment]
Thanks Jakub! I'm glad you approve of my changes. Happy to collaborate more.

For me, the tool was just what I needed (trying to visualize annotations and how they fare during prediction on a large dataset, in order to eradicate inconsistencies in the GT and qualitatively monitor progress with training). Considering the scope of work being done on object detection with COCO format, I think this is important to have, if not crucial.

**Review by i008 — APPROVED** [review]

**Comment by bertsky** [comment]
> Or maybe the IoU selection double slider is too much (esp. for smaller screens)? Having the option to change this on start-up would probably be sufficient... (as is also possible now via `--iou_min`)

@i008 so what's your preference then? Should I revert 8370f5d or keep it? (I've got more changes to propose...)

**Comment by i008** [comment]
> > Or maybe the IoU selection double slider is too much (esp. for smaller screens)? Having the option to change this on start-up would probably be sufficient... (as is also possible now via `--iou_min`)
> 
> @i008 so what's your preference then? Should I revert [8370f5d](https://github.com/i008/COCO-dataset-explorer/commit/8370f5d959eae200350d8b74083a8da56387e6c8) or keep it? (I've got more changes to propose...)

I think they are fine honestly small/low resolutions screens are also rarely a  problem anymore.

**Comment by bertsky** [comment]
> I think they are fine honestly small/low resolutions screens are also rarely a problem anymore.

Agreed. Done.

I've added some more stuff I'd find very useful. Feel free to cherry-pick yourself (or tell me what to drop).

**Comment by i008** [comment]
I will add CI to the project maybe today;)

**Pull request merged**
